version: '3.7'

services:
  postgres: 
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s 
      retries: 5

  server_generator_freq:
    build: .

      # context: .
      # dockerfile: 
      #   ./cmd/client/Dockerfile
    container_name: server_generator
    depends_on:
      - postgres

    # environment:
      # SERVER_TRANSMITTER_HOST: ${SERVER_TRANSMITTER_HOST}
      # SERVER_TRANSMITTER_PORT: ${SERVER_TRANSMITTER_PORT}
      # DB_HOST: ${DB_HOST}
      # DB_PORT: 5432
      # DB_SCHEMA: anomaly
      # DB_USER: ${DB_USER} 
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_SSLMODE: disable



      